# Generated by Django 4.1.3 on 2022-11-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Helper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='No name', max_length=500)),
                ('task_link', models.URLField(max_length=2000)),
                ('start_time', models.TimeField(default='12:00:00')),
                ('sunday', models.BooleanField(default=False)),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
            ],
        ),
    ]
